services:
  webapp:
    image: modiconme/webapp:latest
    container_name: webapp
    ports:
      - "8080:8080"
    networks:
      - webapp-network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_URL=${POSTGRES_URL}"
      - "JWT_SECRET=${JWT_SECRET}"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - webapp-network
    restart: unless-stopped
    volumes:
      - ./pgdata:/data/postgres

networks:
  webapp-network:
    driver: bridge