CREATE TABLE IF NOT EXISTS customer
(
    id         LONG GENERATED BY DEFAULT AS IDENTITY,
    name       TEXT(50)  NOT NULL,
    email      TEXT(50)  NOT NULL,
    age        INT       NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT customer_uq UNIQUE (email)
)